#!/usr/bin/env bash
#!This bash script will displays Best School 10 times but for the 9th iteration will displays Best School and the Hi on a new line
i=0
while (( i  < 10 ));
do
echo "Best School";
if (( i == 8 ));then
echo "Hi"
fi
((i++));
done
