#!/usr/bin/env bash
#This script will displays "Best School" 10 times and 9th line will display "Hi".

i=1
while (( i < 10 ));
do
    echo "Best School";
    if (( i == 8 ));then
	echo "Hi";
    fi
    ((i++));
done
