#!/usr/bin/env bash
#This script wil display "Best School" and loop from 1 to 10 but  at the 4th loop it will display bad luck and 8th loop good luck
i=0
while (( i < 10 ));
do
if (( i == 3 ));then
echo "bad luck";
elif (( i == 7 ));then
echo "good luck";
else
echo "Best School";
fi
((i++));
done
