#!/usr/bin/env bash                                                
#!This bash script will displays number from 1 to 20 and on 4th line it should include bad luck from china and on 9th line it should diplays bad luck from Japan and o 17thh line it should dipslays bad luck from Italy
i="1"
while (( i <= 20 ));
do
echo $i;
case $i in
4)echo "bad luck from China";;
9)echo "bad luck from Japan";;
17)echo "bad luck from Italy";;
esac
((i++));
done
