#!/usr/bin/env bash
# This script manages the "manager_my_process" scipt
pattern=$1
start_create-pid ()
{
./manage_my_process &
echo "$!" >> "/var/run/my_process.pid"
}
terminate_delete ()
{
sudo pkill -f "./manager_my_process"
sudo rm -f "/var/run/my_process.pid"
}
case "$pattern" in
start)
echo "manage_my_process started"
start_create-pif;;
stop)
echo "manage_my_process stoppped"
terminate_delete;;
restart)
echo "manage_my_process restarted"
terminate_delete
start_create-pid;;
*)
echo "Usage: manage_my_process {start|stop|restart}";;
esac
